name: Test

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: python -m pip install --upgrade pip pytest

      - name: Install azurpaint
        run: pip install .

      - name: Run tests
        run: pytest -v -s